# Base Dockerfile for production.
FROM node:18-alpine

WORKDIR /app

# Copy the package manifests.
COPY package.json package-lock.json ./

# Install modules.
RUN npm install --production

# Copy the application code.
COPY . .

# Start the application in production mode.
ENV NODE_ENV production

CMD ["npm", "run", "production"]
